# Generated by Django 5.2.9 on 2026-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nome',), name='uniq_setor_nome_ativo'),
        ),
    ]
