# Generated by Django 5.2.9 on 2026-04-24 10:30

from django.db import migrations, models
from django.utils import timezone


def copy_deleted_flag_to_deleted_at(apps, schema_editor):
    Sector = apps.get_model("employees", "Sector")
    Sector.objects.filter(is_deleted=True).update(deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_sector_is_deleted_alter_sector_nome_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sector',
            name='uniq_setor_nome_ativo',
        ),
        migrations.AddField(
            model_name='sector',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            copy_deleted_flag_to_deleted_at,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='sector',
            name='is_deleted',
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nome',), name='uniq_setor_nome_ativo_nao_excluido'),
        ),
    ]
