# Generated by Django 5.2.9 on 2026-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_sector_uniq_setor_nome_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sector',
            name='uniq_setor_nome_ativo_nao_excluido',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='deleted_at',
            new_name='deactivated_at',
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('nome',), name='uniq_setor_nome_ativo_nao_desativado'),
        ),
    ]
