# Generated by Django 6.0.4 on 2026-04-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_fields_to_created_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.sector'),
        ),
    ]
