# Generated by Django 6.0.4 on 2026-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
