# Generated by Django 6.0.4 on 2026-04-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_deactivated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('horas_segunda', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_terca', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_quarta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_quinta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_sexta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_sabado', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_domingo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.workschedule'),
        ),
    ]
