# Generated by Django 6.0.4 on 2026-04-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_workschedule_employee_work_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('allocation_change', 'Alteracao de setor/escala')], default='allocation_change', max_length=40)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employees.employee')),
                ('new_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_new_sector', to='employees.sector')),
                ('new_work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_new_work_schedule', to='employees.workschedule')),
                ('previous_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_previous_sector', to='employees.sector')),
                ('previous_work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_previous_work_schedule', to='employees.workschedule')),
            ],
            options={
                'ordering': ('-effective_date', '-created_at', '-id'),
            },
        ),
    ]
