# Generated by Django 6.0.4 on 2026-04-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeevent',
            name='bank_hours_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeevent',
            name='event_type',
            field=models.CharField(choices=[('hiring', 'Admissao'), ('allocation_change', 'Alteracao de setor/escala'), ('absence', 'Ausencia'), ('medical_certificate', 'Atestado'), ('bank_hours_adoption', 'Adesao ao banco de horas'), ('bank_hours_withdrawal', 'Saida do banco de horas'), ('bank_hours_movement', 'Movimento de banco de horas'), ('day_off', 'Folga'), ('vacation', 'Ferias'), ('termination', 'Demissao')], default='allocation_change', max_length=40),
        ),
    ]
