# Generated by Django 6.0.4 on 2026-04-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeeevent_bank_hours_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_60_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_100_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('absence_unexcused_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('absence_excused_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('absence_bank_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='employees.employee')),
            ],
            options={
                'ordering': ('-work_date', 'employee__nome_completo', '-id'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='uniq_time_entry_employee_work_date')],
            },
        ),
    ]
