# Generated by Django 6.0.4 on 2026-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeetimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='regime_compensacao_jornada',
            field=models.CharField(choices=[('nao_participante', 'Nao participante'), ('participante', 'Participante')], default='nao_participante', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='tipo',
            field=models.CharField(choices=[('direto', 'Direto'), ('indireto', 'Indireto')], default='direto', max_length=9),
        ),
    ]
