# Generated by Django 6.0.4 on 2026-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_employee_regime_compensacao_jornada_employee_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeetimeentry",
            old_name="work_date",
            new_name="competence_month",
        ),
        migrations.AlterModelOptions(
            name="employeetimeentry",
            options={"ordering": ("-competence_month", "employee__nome_completo", "-id")},
        ),
        migrations.RemoveConstraint(
            model_name="employeetimeentry",
            name="uniq_time_entry_employee_work_date",
        ),
        migrations.AddConstraint(
            model_name="employeetimeentry",
            constraint=models.UniqueConstraint(
                fields=("employee", "competence_month"),
                name="uniq_time_entry_employee_competence_month",
            ),
        ),
    ]
