# Generated by Django 6.0.4 on 2026-04-24 15:10

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def convert_hours_to_minutes(apps, schema_editor):
    EmployeeTimeEntry = apps.get_model("employees", "EmployeeTimeEntry")

    def hours_to_minutes(value):
        if value is None:
            return 0
        return int(
            (Decimal(value) * Decimal("60")).quantize(
                Decimal("1"),
                rounding=ROUND_HALF_UP,
            )
        )

    for entry in EmployeeTimeEntry.objects.all().iterator():
        entry.regular_minutes = hours_to_minutes(getattr(entry, "regular_hours", 0))
        entry.overtime_60_minutes = hours_to_minutes(
            getattr(entry, "overtime_60_hours", 0)
        )
        entry.overtime_100_minutes = hours_to_minutes(
            getattr(entry, "overtime_100_hours", 0)
        )
        entry.absence_unexcused_minutes = hours_to_minutes(
            getattr(entry, "absence_unexcused_hours", 0)
        )
        entry.absence_excused_minutes = hours_to_minutes(
            getattr(entry, "absence_excused_hours", 0)
        )
        entry.absence_bank_minutes = hours_to_minutes(
            getattr(entry, "absence_bank_hours", 0)
        )
        entry.save(
            update_fields=[
                "regular_minutes",
                "overtime_60_minutes",
                "overtime_100_minutes",
                "absence_unexcused_minutes",
                "absence_excused_minutes",
                "absence_bank_minutes",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_rename_work_date_to_competence_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetimeentry",
            name="regular_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeetimeentry",
            name="overtime_60_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeetimeentry",
            name="overtime_100_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeetimeentry",
            name="absence_unexcused_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeetimeentry",
            name="absence_excused_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employeetimeentry",
            name="absence_bank_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(convert_hours_to_minutes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="regular_hours",
        ),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="overtime_60_hours",
        ),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="overtime_100_hours",
        ),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="absence_unexcused_hours",
        ),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="absence_excused_hours",
        ),
        migrations.RemoveField(
            model_name="employeetimeentry",
            name="absence_bank_hours",
        ),
    ]
