# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_convert_timeentry_hours_to_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.AddField(
            model_name="workschedule",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_schedules",
                to="employees.workcalendar",
            ),
        ),
        migrations.CreateModel(
            name="WorkCalendarPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("holiday", "Feriado"),
                            ("bridge", "Ponte"),
                            ("collective_vacation", "Ferias coletivas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("description", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="employees.workcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="work_calendar_period_end_after_start",
                    )
                ],
            },
        ),
    ]
