# Generated by Django 6.0.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0016_workcalendar_and_workcalendarperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetMonthClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence_month", models.DateField(db_index=True, unique=True)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-competence_month", "-closed_at", "-id"),
            },
        ),
    ]
