import django.db.models.deletion
# Generated by Django 6.0.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0017_timesheetmonthclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetMonthClosureWorkScheduleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_work_schedule_id", models.IntegerField(db_index=True)),
                ("work_schedule_name", models.CharField(max_length=120)),
                (
                    "source_calendar_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("calendar_name", models.CharField(blank=True, max_length=120)),
                ("horas_segunda", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_terca", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_quarta", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_quinta", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_sexta", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_sabado", models.DecimalField(decimal_places=2, max_digits=4)),
                ("horas_domingo", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "closure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule_snapshots",
                        to="employees.timesheetmonthclosure",
                    ),
                ),
            ],
            options={
                "ordering": ("closure__competence_month", "work_schedule_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="TimesheetMonthClosureCalendarPeriodSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_calendar_id", models.IntegerField(db_index=True)),
                ("calendar_name", models.CharField(max_length=120)),
                ("period_type", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=150)),
                (
                    "closure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_period_snapshots",
                        to="employees.timesheetmonthclosure",
                    ),
                ),
            ],
            options={
                "ordering": ("closure__competence_month", "start_date", "id"),
            },
        ),
    ]
