# Generated by Django 6.0.4 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0018_timesheetmonthclosuresnapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetMonthClosureEmployeeEventSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_employee_event_id", models.IntegerField(db_index=True)),
                ("source_employee_id", models.IntegerField(db_index=True)),
                ("employee_registration", models.CharField(max_length=50)),
                ("employee_name", models.CharField(max_length=150)),
                ("event_type", models.CharField(max_length=40)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "closure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_event_snapshots",
                        to="employees.timesheetmonthclosure",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "closure__competence_month",
                    "employee_name",
                    "effective_date",
                    "source_employee_event_id",
                ),
            },
        ),
    ]
