# Generated by Django 5.2.9 on 2026-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_timesheetmonthclosureemployeeeventsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeevent',
            name='event_type',
            field=models.CharField(choices=[('hiring', 'Admissao'), ('allocation_change', 'Alteracao de setor/escala'), ('absence', 'Afastamento'), ('medical_certificate', 'Atestado'), ('bank_hours_adoption', 'Adesao ao banco de horas'), ('bank_hours_withdrawal', 'Saida do banco de horas'), ('bank_hours_movement', 'Movimento de banco de horas'), ('day_off', 'Folga'), ('vacation', 'Ferias'), ('termination', 'Demissao')], default='allocation_change', max_length=40),
        ),
    ]
