# Generated by Django 6.0.4 on 2026-04-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employeeevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('nome',), name='uniq_cargo_nome_ativo_nao_desativado')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.cargo'),
        ),
    ]
