# Generated by Django 6.0.4 on 2026-05-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_bankhoursrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoursSemesterClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('semester', models.IntegerField(choices=[(1, '1o semestre'), (2, '2o semestre')], db_index=True)),
                ('adjustment_month', models.DateField(db_index=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reversed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-closed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankHoursSemesterClosureAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closing_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_hours_closing_adjustments', to='employees.employeeevent')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='employees.bankhourssemesterclosure')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_hours_semester_adjustments', to='employees.employee')),
                ('reversal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_hours_reversal_adjustments', to='employees.employeeevent')),
            ],
            options={
                'ordering': ('closure_id', 'employee__nome_completo', 'id'),
            },
        ),
    ]
