# Generated by Django 5.2.9 on 2026-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_bankhourssemesterclosure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula__isnull', False)), fields=('matricula',), name='uniq_employee_matricula_not_null'),
        ),
    ]
