# Generated by Django 6.0.4 on 2026-05-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_employee_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departamentos',
                'ordering': ('nome',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='uniq_setor_nome_ativo_nao_desativado',
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('nome',), name='uniq_area_nome_ativo_nao_desativado'),
        ),
        migrations.AddField(
            model_name='department',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='employees.area'),
        ),
        migrations.AddField(
            model_name='sector',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='employees.department'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('department', 'nome'), name='uniq_setor_departamento_nome_ativo_nao_desativado'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('area', 'nome'), name='uniq_departamento_area_nome_ativo_nao_desativado'),
        ),
    ]
