# Generated by Django 5.2.9 on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0025_area_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetImportReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence_month", models.DateField(db_index=True)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("file_period_start", models.DateField(blank=True, null=True)),
                ("file_period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("applied_entries_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TimesheetImportReportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_type",
                    models.CharField(
                        choices=[
                            ("imported", "Apto para importar"),
                            ("skipped", "Com problema"),
                            ("missing_in_import", "Ausente no arquivo"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("registration", models.CharField(blank=True, max_length=50)),
                ("employee_name", models.CharField(blank=True, max_length=150)),
                ("regular_minutes", models.IntegerField(default=0)),
                ("overtime_60_minutes", models.IntegerField(default=0)),
                ("overtime_100_minutes", models.IntegerField(default=0)),
                ("absence_unexcused_minutes", models.IntegerField(default=0)),
                ("absence_excused_minutes", models.IntegerField(default=0)),
                ("absence_bank_minutes", models.IntegerField(default=0)),
                ("issues", models.JSONField(blank=True, default=list)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_import_report_rows",
                        to="employees.employee",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="employees.timesheetimportreport",
                    ),
                ),
            ],
            options={
                "ordering": ("report_id", "sort_order", "id"),
            },
        ),
    ]
