"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v^)vip^$l581psghib5*j(7$vaffltbmy=839v1@0hvs7z1=s('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

allowed_hosts_from_env = os.getenv("DJANGO_ALLOWED_HOSTS", "").strip()
if allowed_hosts_from_env:
    ALLOWED_HOSTS = [
        host.strip()
        for host in allowed_hosts_from_env.split(",")
        if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "192.168.0.74",
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employees',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DEFAULT_SQLITE_PATH = DATA_DIR / "rh.db"


def _build_online_database() -> dict:
    engine = os.getenv("DB_ENGINE", "django.db.backends.sqlite3").strip()
    name = os.getenv("DB_NAME", "").strip()

    if engine == "django.db.backends.sqlite3":
        return {
            "ENGINE": engine,
            "NAME": name or str(DEFAULT_SQLITE_PATH),
        }

    database_config = {
        "ENGINE": engine,
        "NAME": name,
    }
    for env_key, setting_key in [
        ("DB_USER", "USER"),
        ("DB_PASSWORD", "PASSWORD"),
        ("DB_HOST", "HOST"),
        ("DB_PORT", "PORT"),
    ]:
        value = os.getenv(env_key, "").strip()
        if value:
            database_config[setting_key] = value
    return database_config


def _build_database() -> dict:
    mode = os.getenv("DATABASE_MODE", "arquivo").strip().lower()
    if mode == "online":
        return _build_online_database()

    db_file_path = os.getenv("DB_FILE_PATH", "").strip()
    if db_file_path:
        candidate = Path(db_file_path).expanduser()
        if not candidate.is_absolute():
            candidate = BASE_DIR / candidate
        try:
            sqlite_path = candidate.resolve(strict=False)
        except OSError:
            sqlite_path = DEFAULT_SQLITE_PATH
    else:
        sqlite_path = DEFAULT_SQLITE_PATH

    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(sqlite_path),
    }


DATABASES = {
    "default": _build_database(),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
