from django.urls import path
from django.views.generic import RedirectView

from .views import (
    area_create,
    area_deactivate,
    area_activate,
    area_edit,
    bank_hours_closure_page,
    bank_hours_page,
    bank_hours_rule_delete,
    bank_hours_rules_page,
    cargo_activate,
    cargo_deactivate,
    cargo_edit_page,
    cargos_page,
    department_create,
    department_deactivate,
    department_activate,
    department_edit,
    employee_activate,
    employee_create_sector,
    employee_deactivate,
    employee_edit_page,
    employees_page,
    events_page,
    sector_activate,
    sector_deactivate,
    sector_edit_page,
    sectors_page,
    timesheet_page,
    timesheet_dashboard_page,
    timesheet_snapshots_audit_page,
    work_schedules_page,
)

urlpatterns = [
    path("", employees_page, name="home"),
    path("empregados/", employees_page, name="employees_page"),
    path("empregados/cargos/", cargos_page, name="cargos_page"),
    path("empregados/cargos/<int:cargo_id>/editar/", cargo_edit_page, name="cargo_edit_page"),
    path("empregados/cargos/<int:cargo_id>/desativar/", cargo_deactivate, name="cargo_deactivate"),
    path("empregados/cargos/<int:cargo_id>/ativar/", cargo_activate, name="cargo_activate"),
    path("empregados/setores/novo/", employee_create_sector, name="employee_create_sector"),
    path("empregados/<int:employee_id>/editar/", employee_edit_page, name="employee_edit_page"),
    path("empregados/<int:employee_id>/desativar/", employee_deactivate, name="employee_deactivate"),
    path("empregados/<int:employee_id>/ativar/", employee_activate, name="employee_activate"),
    path("eventos/", events_page, name="events_page"),
    path("timesheet/", timesheet_page, name="timesheet_page"),
    path("banco-horas/", bank_hours_page, name="bank_hours_page"),
    path("banco-horas/encerramento/", bank_hours_closure_page, name="bank_hours_closure_page"),
    path("banco-horas/regras/", bank_hours_rules_page, name="bank_hours_rules_page"),
    path("banco-horas/regras/<int:rule_id>/excluir/", bank_hours_rule_delete, name="bank_hours_rule_delete"),
    path("timesheet/dashboard/", timesheet_dashboard_page, name="timesheet_dashboard_page"),
    path("timesheet/snapshots/", timesheet_snapshots_audit_page, name="timesheet_snapshots_audit_page"),
    path(
        "ponto/",
        RedirectView.as_view(pattern_name="timesheet_page", permanent=True, query_string=True),
    ),
    path(
        "ausencias/",
        RedirectView.as_view(pattern_name="events_page", permanent=True, query_string=True),
    ),
    path("setores/", sectors_page, name="sectors_page"),
    path("setores/areas/novo/", area_create, name="area_create"),
    path("setores/areas/<int:area_id>/editar/", area_edit, name="area_edit"),
    path("setores/areas/<int:area_id>/desativar/", area_deactivate, name="area_deactivate"),
    path("setores/areas/<int:area_id>/ativar/", area_activate, name="area_activate"),
    path("setores/departamentos/novo/", department_create, name="department_create"),
    path("setores/departamentos/<int:department_id>/editar/", department_edit, name="department_edit"),
    path("setores/departamentos/<int:department_id>/desativar/", department_deactivate, name="department_deactivate"),
    path("setores/departamentos/<int:department_id>/ativar/", department_activate, name="department_activate"),
    path("setores/<int:sector_id>/editar/", sector_edit_page, name="sector_edit_page"),
    path("setores/<int:sector_id>/desativar/", sector_deactivate, name="sector_deactivate"),
    path("setores/<int:sector_id>/ativar/", sector_activate, name="sector_activate"),
    path("escalas/", work_schedules_page, name="work_schedules_page"),
]
